### ISSUE TITLE
shrinkwrap version wrong

### ISSUE THREAD

**Issue by mrac** [bbyars/mountebank#153] opened 2016-06-27 08:51 UTC
#### Expected behaviour
Version referenced in `npm-shrinkwrap.json` should match the version in `package.json`.
For **release ver.1.5.1** it's not the case.

Shrinkwrap version should be:
```
{
  "name": "mountebank",
  "version": "1.5.1",
  "dependencies": {
```

#### Actual behaviour
Shrinkwrap version is 1.6.0 which is incorrect:

```
{
  "name": "mountebank",
  "version": "1.6.0",
  "dependencies": {
```

Running `npm shrinkwrap` causes:

```

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: abab@1.0.3 /Users/wr/ccat2/node_modules/mountebank/node_modules/abab
npm ERR! extraneous: acorn-globals@1.0.9 /Users/wr/ccat2/node_modules/mountebank/node_modules/acorn-globals
npm ERR! extraneous: array-equal@1.0.0 /Users/wr/ccat2/node_modules/mountebank/node_modules/array-equal
npm ERR! extraneous: clean-css@0.9.1 /Users/wr/ccat2/node_modules/mountebank/node_modules/clean-css
npm ERR! extraneous: coffee-script@1.10.0 /Users/wr/ccat2/node_modules/mountebank/node_modules/coffee-script
npm ERR! extraneous: csslint@0.10.0 /Users/wr/ccat2/node_modules/mountebank/node_modules/csslint
npm ERR! extraneous: cssstyle@0.2.34 /Users/wr/ccat2/node_modules/mountebank/node_modules/cssstyle
npm ERR! extraneous: date-time@1.0.0 /Users/wr/ccat2/node_modules/mountebank/node_modules/date-time
npm ERR! extraneous: dateformat@1.0.12 /Users/wr/ccat2/node_modules/mountebank/node_modules/dateformat
npm ERR! extraneous: diff@1.4.0 /Users/wr/ccat2/node_modules/mountebank/node_modules/diff
npm ERR! extraneous: escodegen@1.8.0 /Users/wr/ccat2/node_modules/mountebank/node_modules/escodegen
npm ERR! extraneous: eslint@2.8.0 /Users/wr/ccat2/node_modules/mountebank/node_modules/eslint
npm ERR! extraneous: eventemitter2@0.4.14 /Users/wr/ccat2/node_modules/mountebank/node_modules/eventemitter2
npm ERR! extraneous: fileset@0.2.1 /Users/wr/ccat2/node_modules/mountebank/node_modules/fileset
npm ERR! extraneous: growl@1.8.1 /Users/wr/ccat2/node_modules/mountebank/node_modules/growl
npm ERR! extraneous: grunt-cli@1.2.0 /Users/wr/ccat2/node_modules/mountebank/node_modules/grunt-cli
npm ERR! extraneous: grunt-legacy-log@1.0.0 /Users/wr/ccat2/node_modules/mountebank/node_modules/grunt-legacy-log
npm ERR! extraneous: grunt-legacy-util@1.0.0 /Users/wr/ccat2/node_modules/mountebank/node_modules/grunt-legacy-util
npm ERR! extraneous: gzip-js@0.3.1 /Users/wr/ccat2/node_modules/mountebank/node_modules/gzip-js
npm ERR! extraneous: handlebars@4.0.5 /Users/wr/ccat2/node_modules/mountebank/node_modules/handlebars
npm ERR! extraneous: has-flag@1.0.0 /Users/wr/ccat2/node_modules/mountebank/node_modules/has-flag
npm ERR! extraneous: jade@0.26.3 /Users/wr/ccat2/node_modules/mountebank/node_modules/jade
npm ERR! extraneous: js-yaml@3.0.1 /Users/wr/ccat2/node_modules/mountebank/node_modules/js-yaml
npm ERR! extraneous: jsdoc@3.4.0 /Users/wr/ccat2/node_modules/mountebank/node_modules/jsdoc
npm ERR! extraneous: jsonfile@2.3.0 /Users/wr/ccat2/node_modules/mountebank/node_modules/jsonfile
npm ERR! extraneous: klaw@1.2.0 /Users/wr/ccat2/node_modules/mountebank/node_modules/klaw
npm ERR! extraneous: lcov-parse@0.0.6 /Users/wr/ccat2/node_modules/mountebank/node_modules/lcov-parse
npm ERR! extraneous: log-driver@1.2.4 /Users/wr/ccat2/node_modules/mountebank/node_modules/log-driver
npm ERR! extraneous: nwmatcher@1.3.7 /Users/wr/ccat2/node_modules/mountebank/node_modules/nwmatcher
npm ERR! extraneous: parse5@1.5.1 /Users/wr/ccat2/node_modules/mountebank/node_modules/parse5
npm ERR! extraneous: pretty-ms@2.1.0 /Users/wr/ccat2/node_modules/mountebank/node_modules/pretty-ms
npm ERR! extraneous: sigmund@1.0.1 /Users/wr/ccat2/node_modules/mountebank/node_modules/sigmund
npm ERR! extraneous: superagent@0.21.0 /Users/wr/ccat2/node_modules/mountebank/node_modules/superagent
npm ERR! extraneous: superagent-proxy@0.3.2 /Users/wr/ccat2/node_modules/mountebank/node_modules/superagent-proxy
npm ERR! extraneous: symbol-tree@3.1.4 /Users/wr/ccat2/node_modules/mountebank/node_modules/symbol-tree
npm ERR! extraneous: whatwg-url@1.0.1 /Users/wr/ccat2/node_modules/mountebank/node_modules/whatwg-url
npm ERR! extraneous: xml-name-validator@2.0.1 /Users/wr/ccat2/node_modules/mountebank/node_modules/xml-name-validator
```

...

#### Steps to reproduce
`npm shrinkwrap` will fail for packages depending on mountebank.

...

#### Software versions used

```
OS         : Mac OS
mountebank : 1.5.1
node.js    :  5.5.0
```

**Comment by mattherman** [comment] 2016-10-07 01:31
It looks like this might be a duplicate of #120

**Closed** 2016-10-11 13:48 UTC
