### ISSUE TITLE
Option to allow predicateGenerators to save body in separate files

### ISSUE THREAD

**Issue by lyricnz** [bbyars/mountebank#249] opened 2017-06-03 22:31 UTC
Rather than always including the response body inline, it would be useful to be able to generate these into separate files that are <% include .. %> possibly with stringify() for text fields or a base64 encode for binary fields. This would allow the body to be more readily viewed/modified on a saved dataset.  Given interface is primarily HTTP, perhaps this is only an option for "mb save" command line.

**Comment by bbyars** [comment] 2017-06-03 23:50
Duplicate of https://github.com/bbyars/mountebank/issues/177, which I believe someone is working on now. I'll move the request to that issue.

**Closed by bbyars** 2017-06-03 23:50 UTC

**Comment by lyricnz** [comment] 2017-06-05 23:32
Thinking about this a bit more, I'm less sure it's a good idea. Using external files makes it harder to update a running mountebank via HTTP.
