### ISSUE TITLE
Unable to require module within response injection in v1.11.0

### ISSUE THREAD

**Issue by mattherman** [bbyars/mountebank#268] opened 2017-07-19 21:18 UTC
I was previously using mountebank v1.4.3. With that version I was able to create an imposter that required and used a Node module (in this case "underscore").

Injection Function:
```
function(request, state, logger) {
    var _ = require('underscore');
    var parsedBody = JSON.parse(request.body);
    var squared = _.map(parsedBody, function(val) {
        return val*val;
    });
    return {
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(squared)
    };
 }
```

Full Imposter:
```
{
	"port": "4545",
	"protocol": "http",
	"name": "Arithmetic Service",
	"stubs": [
		{
			"responses": [
                {
                    "inject": "function(request, state, logger) {var _ = require('underscore');var parsedBody = JSON.parse(request.body);var squared = _.map(parsedBody, function(val) {return val*val;});return {headers: { 'Content-Type': 'application/json' },body: JSON.stringify(squared)};}"
                }
			],
			"predicates": [
				{
					"and": [
						{
							"equals": {
								"method": "POST"
							}
						},
						{
							"contains": {
								"path": "/api/square"
							}
						}
					]
				}
            ]
        }
    ]
}
```

Once I upgrade mountebank to v1.11.0, this same imposter throws "invalid injection" errors whenever requests are made to it with the message "Cannot find module 'underscore'".

Error (full log below):
```
{
	"code": "invalid injection",
	"
message": "invalid response injection",
	"source": "(function(request, state, logger
) {var _ = require('underscore');var parsedBody = JSON.parse(request.body);var s
quared = _.map(parsedBody, function(val) {return val*val;});return {headers: { '
Content-Type': 'application/json' },body: JSON.stringify(squared)};})(scope, inj
ectState, logger, deferred.resolve, imposterState);",
	"data": "Cannot find module
'underscore'",
	"name": "Error",
	"stack": "Error\n    at Object.from (C:\\Mountebank\
\mountebank-v1.11.0-win-x86\\mountebank\\src\\util\\inherit.js:15:17)\n    at cr
eateError (C:\\Mountebank\\mountebank-v1.11.0-win-x86\\mountebank\\src\\util\\er
rors.js:10:26)\n    at Object.InjectionError (C:\\Mountebank\\mountebank-v1.11.0
-win-x86\\mountebank\\src\\util\\errors.js:25:16)\n    at inject (C:\\Mountebank
\\mountebank-v1.11.0-win-x86\\mountebank\\src\\models\\responseResolver.js:43:44
)\n    at processResponse (C:\\Mountebank\\mountebank-v1.11.0-win-x86\\mounteban
k\\src\\models\\responseResolver.js:237:20)\n    at Object.resolve (C:\\Mounteba
nk\\mountebank-v1.11.0-win-x86\\mountebank\\src\\models\\responseResolver.js:271
:16)\n    at Object.resolve (C:\\Mountebank\\mountebank-v1.11.0-win-x86\\mounteb
ank\\src\\models\\stubRepository.js:124:18)\n    at EventEmitter.respond (C:\\Mo
untebank\\mountebank-v1.11.0-win-x86\\mountebank\\src\\models\\http\\baseHttpSer
ver.js:78:34)\n    at C:\\Mountebank\\mountebank-v1.11.0-win-x86\\mountebank\\sr
c\\models\\abstractServer.js:96:35\n    at _fulfilled (C:\\Mountebank\\mounteban
k-v1.11.0-win-x86\\mountebank\\node_modules\\q\\q.js:854:54)"
}
```

Is this a bug? I wasn't able to find anything in the docs that would indicate I could no longer reference modules that way.

#### Software versions used

```
OS         : Windows 7
mountebank : 1.4.3 and 1.11.0
Installation method : zip
```

#### Log contents in mb.log when running mb --loglevel debug

```
C:\Mountebank\mountebank-v1.11.0-win-x86>mb --allowInjection --loglevel debug
info: [mb:2525] mountebank v1.11.0 now taking orders - point your browser to htt
p://localhost:2525 for help
debug: [mb:2525] config: {"options":{"allowInjection":true,"loglevel":"debug","p
ort":2525,"noParse":false,"pidfile":"mb.pid","nologfile":false,"logfile":"mb.log
","localOnly":false,"ipWhitelist":["*"],"mock":false,"debug":false,"heroku":fals
e},"process":{"nodeVersion":"v6.10.3","architecture":"ia32","platform":"win32"}}

warn: [mb:2525] Running with --allowInjection set. See http://localhost:2525/doc
s/security for security info
info: [mb:2525] POST /imposters
debug: [mb:2525] ::1:9288 => {"port":"4545","protocol":"http","name":"Arithmetic
 Service","stubs":[{"responses":[{"inject":"function(request, state, logger) {va
r _ = require('underscore');var parsedBody = JSON.parse(request.body);var square
d = _.map(parsedBody, function(val) {return val*val;});return {headers: { 'Conte
nt-Type': 'application/json' },body: JSON.stringify(squared)};}"}],"predicates":
[{"and":[{"equals":{"method":"POST"}},{"contains":{"path":"/api/square"}}]}]}]}
info: [http:4545 Arithmetic Service] Open for business...
debug: [http:4545 Arithmetic Service] ::1:9292 ESTABLISHED
info: [http:4545 Arithmetic Service] ::1:9292 => POST /api/square
debug: [http:4545 Arithmetic Service] ::1:9292 => {"requestFrom":"::1:9292","met
hod":"POST","path":"/api/square","query":{},"headers":{"Host":"localhost:4545","
Connection":"keep-alive","Content-Length":"8","Postman-Token":"f4205ee4-e798-482
0-6cd1-d29ebff77ae6","Cache-Control":"no-cache","Origin":"chrome-extension://fhb
jgbiflinjbdggehcddcbncdddomop","User-Agent":"Mozilla/5.0 (Windows NT 6.1; Win64;
 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
,"Content-Type":"application/json","Accept":"*/*","Accept-Encoding":"gzip, defla
te, br","Accept-Language":"en-US,en;q=0.8"},"body":"[2,4,10]"}
debug: [http:4545 Arithmetic Service] ::1:9292 using predicate match: [{"and":[{
"equals":{"method":"POST"}},{"contains":{"path":"/api/square"}}]}]
debug: [http:4545 Arithmetic Service] ::1:9292 generating response from {"inject
":"function(request, state, logger) {var _ = require('underscore');var parsedBod
y = JSON.parse(request.body);var squared = _.map(parsedBody, function(val) {retu
rn val*val;});return {headers: { 'Content-Type': 'application/json' },body: JSON
.stringify(squared)};}"}
error: [http:4545 Arithmetic Service] ::1:9292 injection X=> Error: Cannot find
module 'underscore'
error: [http:4545 Arithmetic Service] ::1:9292     full source: "(function(reque
st, state, logger) {var _ = require('underscore');var parsedBody = JSON.parse(re
quest.body);var squared = _.map(parsedBody, function(val) {return val*val;});ret
urn {headers: { 'Content-Type': 'application/json' },body: JSON.stringify(square
d)};})(scope, injectState, logger, deferred.resolve, imposterState);"
error: [http:4545 Arithmetic Service] ::1:9292     scope: {"requestFrom":"::1:92
92","method":"POST","path":"/api/square","query":{},"headers":{"Host":"localhost
:4545","Connection":"keep-alive","Content-Length":"8","Postman-Token":"f4205ee4-
e798-4820-6cd1-d29ebff77ae6","Cache-Control":"no-cache","Origin":"chrome-extensi
on://fhbjgbiflinjbdggehcddcbncdddomop","User-Agent":"Mozilla/5.0 (Windows NT 6.1
; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari
/537.36","Content-Type":"application/json","Accept":"*/*","Accept-Encoding":"gzi
p, deflate, br","Accept-Language":"en-US,en;q=0.8"},"body":"[2,4,10]"}
error: [http:4545 Arithmetic Service] ::1:9292     injectState: {}
error: [http:4545 Arithmetic Service] ::1:9292     imposterState: {}
error: [http:4545 Arithmetic Service] ::1:9292 X=> {"code":"invalid injection","
message":"invalid response injection","source":"(function(request, state, logger
) {var _ = require('underscore');var parsedBody = JSON.parse(request.body);var s
quared = _.map(parsedBody, function(val) {return val*val;});return {headers: { '
Content-Type': 'application/json' },body: JSON.stringify(squared)};})(scope, inj
ectState, logger, deferred.resolve, imposterState);","data":"Cannot find module
'underscore'","name":"Error","stack":"Error\n    at Object.from (C:\\Mountebank\
\mountebank-v1.11.0-win-x86\\mountebank\\src\\util\\inherit.js:15:17)\n    at cr
eateError (C:\\Mountebank\\mountebank-v1.11.0-win-x86\\mountebank\\src\\util\\er
rors.js:10:26)\n    at Object.InjectionError (C:\\Mountebank\\mountebank-v1.11.0
-win-x86\\mountebank\\src\\util\\errors.js:25:16)\n    at inject (C:\\Mountebank
\\mountebank-v1.11.0-win-x86\\mountebank\\src\\models\\responseResolver.js:43:44
)\n    at processResponse (C:\\Mountebank\\mountebank-v1.11.0-win-x86\\mounteban
k\\src\\models\\responseResolver.js:237:20)\n    at Object.resolve (C:\\Mounteba
nk\\mountebank-v1.11.0-win-x86\\mountebank\\src\\models\\responseResolver.js:271
:16)\n    at Object.resolve (C:\\Mountebank\\mountebank-v1.11.0-win-x86\\mounteb
ank\\src\\models\\stubRepository.js:124:18)\n    at EventEmitter.respond (C:\\Mo
untebank\\mountebank-v1.11.0-win-x86\\mountebank\\src\\models\\http\\baseHttpSer
ver.js:78:34)\n    at C:\\Mountebank\\mountebank-v1.11.0-win-x86\\mountebank\\sr
c\\models\\abstractServer.js:96:35\n    at _fulfilled (C:\\Mountebank\\mounteban
k-v1.11.0-win-x86\\mountebank\\node_modules\\q\\q.js:854:54)"}
debug: [http:4545 Arithmetic Service] ::1:9292 CLOSED
```

**Comment by plee-nm** [comment] 2017-07-20 21:25
My guess is that this was just working by accident, mb must have removed their dependency on underscore.  I recently just asked to help develop a feature that can make the code you are trying to do easier and future proof.  

https://github.com/bbyars/mountebank/issues/263

**Comment by FrancisBaileyH** [comment] 2017-07-20 23:16
As a quick work around you can install your package in the global directory:
```
npm install -g underscore
```
and then set the node path, and it should work:
```
export NODE_PATH=$(npm root --quiet -g)
```

**Comment by bbyars** [comment] 2017-07-22 18:24
Underscore was never directly included in mountebank, but was probably transitively depended on by a module mountebank imported. I'll document how to import other npm modules, but @FrancisBaileyH comment is correct. Using a global install, or directly fiddling with the install directory of mountebank, are the only two ways. I'm closing this issue because it's working as designed.

@plee-nm: Thanks for the prod. I'm going through issues today and will respond to #263 shortly.

**Closed by bbyars** 2017-07-22 18:24 UTC
