### ISSUE TITLE
Mountebank can't find matched predicate for request with null value properties

### ISSUE THREAD

**Issue by bazaka** [bbyars/mountebank#252] opened 2017-06-09 11:41 UTC
Incorrect comparison of request with null values

#### Steps to reproduce

1. Post imposter
`"stubs": [
    {
      "predicates": [
        {
          "equals": {
            "method": "post",
            "path": "/passwordresetunknown",
            "body": {
              "UserId": null,
              "DisplayName": null,
              "EmailAddress": "unknownuser@asd.com",
              "ResetLink": null
            }
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 200,
            "body": "messageId"
          }
        }
      ]
    }`

2. Make post request
```
{
              "UserId": null,
              "DisplayName": null,
              "EmailAddress": "unknownuser@asd.com",
              "ResetLink": null
            }
```
3. Actual result:
` [http:5000 DefaultMock] ::ffff:172.27.0.1:58886 no predicate match`

#### Software versions used
OS         : Win10
mountebank : 1.11
```
```

#### Log contents in mb.log when running mb --loglevel debug

```
email_1                  | debug: [http:5000 DefaultMock] ::ffff:172.27.0.1:58886 => {"requestFrom":"::ffff:172.27.0.1:5
8886","method":"POST","path":"/passwordresetunknown","query":{},"headers":{"Host":"email:5556","Connection":"keep-alive"
,"Content-Length":"167","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) C
hrome/58.0.3029.110 Safari/537.36","Cache-Control":"no-cache","Origin":"chrome-extension://fhbjgbiflinjbdggehcddcbncdddo
mop","Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjYzZWIzMzcxZDQ0OTc5OGI4NDM1M
DJlZDlmOGU4MmZkODQ3YWZkOWU2ZTdjNjUwYWZlMGMxODkyM2M4M2ZmNjUiLCJ0eXAiOiJKV1QifQ.eyJuYmYiOjE0OTcwMDgwMTEsImV4cCI6MTQ5NzAxMT
YxMSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QvcmVzb3VyY2VzIiwiY2xpZW50X2lkIjoiY2xpZW50Iiwic3ViIj
oiMTYwNWQxYWQtOWRjNS00MzQzLWIyOGMtYmVkNzNmYjM1YTIyIiwiYXV0aF90aW1lIjoiLTg1ODcwNDU5ODg3Mzk3NjQ0OTgiLCJpZHAiOiJJZF9Qcm92aW
RlciIsInNjb3BlIjpbImlwcmVvYWNjb3VudC1rZXl2YWx1ZXN0b3JlIiwiaXByZW9hY2NvdW50LXVzZXJzdG9yZSIsImlwcmVvYWNjb3VudC11c2VybWFuYW
dlbWVudCIsImlwcmVvYWNjb3VudC1pbnZpdGF0aW9uLXByb2Nlc3NpbmciLCJpcHJlb2FjY291bnQtcHJvZHVjdG9uYm9hcmRpbmdzZXR0aW5ncyIsImlwcm
VvYWNjb3VudC1wcm9kdWN0b25ib2FyZGluZ3NldHRpbmdzLXJlYWQiLCJvcGVuaWQiLCJwcm9maWxlIiwiZW1haWwiLCJpcHJlb2FjY291bnQtZW1haWwiLC
JpcHJlb2FjY291bnQtZW1haWwtZGlzcGF0Y2hlciJdLCJhbXIiOlsiQXV0aF9NZXRob2QiXX0.DkYA23c7ztMjiVe3LqCQHDifAfca30rGFqdrD5iwHrlLmS
CxFd2bX0sl_KMsNzO_h9xxZGlXgzmnBeOtpSp6vZ2xQjRB2TIFEMSp97wBtDInEtceiaWDhy3iiJXMO1SW8IAKCQnTEcNa2VpsVDsGCACCmZyBQl68MATedC
0bKRLSpGCOvTnLm6xFq2rqu6FqLzG9OYLQGyd_1yUo2BNkO-SO9UXFjURygzfu-GU1-XtCKs_XjnQ47grjJmPMudjrGhoIxxqjY8PFOtbIJuZzFxpcP7rWCM
Wxnnnojh4kSzuUGNa69f33Zk8OuYvQFhLMN3yi_yO_r87Gc80NR6mJxw","Postman-Token":"fa2408d8-5090-6e46-b48a-d3b589bc87cb","Accept
":"*/*","Accept-Encoding":"gzip, deflate","Accept-Language":"en-US,en;q=0.8,ru;q=0.6,uk;q=0.4"},"body":"{\n
 \"UserId\": null,\n              \"DisplayName\": null,\n              \"EmailAddress\": \"unknownuser@asd.com\",\n
            \"ResetLink\": null\n            }"}
email_1                  | debug: [http:5000 DefaultMock] ::ffff:172.27.0.1:58886 no predicate match
email_1                  | debug: [http:5000 DefaultMock] ::ffff:172.27.0.1:58886 generating response from {"is":{}}
email_1                  | debug: [http:5000 DefaultMock] ::ffff:172.27.0.1:58886 <= {"statusCode":200,"headers":{"Conne
ction":"close"},"body":"","_mode":"text"}
email_1                  | debug: [http:5000 DefaultMock] ::ffff:172.27.0.1:58886 CLOSED```

**Comment by bbyars** [comment] 2017-06-11 19:25
Thanks. Will aim to get this fixed in the next release.

**Comment by bbyars** [comment] 2017-07-22 19:38
duplicate of #262

**Closed by bbyars** 2017-07-22 19:38 UTC
